# Generated by Django 3.0.3 on 2021-03-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_auto_20210324_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
